language: generic
sudo : required
services:
  - docker

before_install:
  - docker build -t ebigh1368/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ebigh1368/docker-react npm run test -- --coverage